# Generated by Django 4.1.7 on 2023-03-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tcr_name", models.CharField(max_length=50)),
                ("tcr_info", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "teacher",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "user_course",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VideoWatches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isfullywatched",
                    models.IntegerField(
                        blank=True, db_column="isFullyWatched", null=True
                    ),
                ),
            ],
            options={
                "db_table": "video_watches",
                "managed": False,
            },
        ),
    ]
