# Generated by Django 4.1.7 on 2023-03-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"managed": True},
        ),
    ]
