# Generated by Django 4.1.7 on 2023-03-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_videowatches_usercourse_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="tcr_img",
            field=models.TextField(blank=True, null=True),
        ),
    ]
