# Generated by Django 4.1.7 on 2023-03-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_videowatches_usercourse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
