# Generated by Django 4.1.7 on 2023-03-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videowatches",
            name="isfullywatched",
            field=models.BooleanField(
                blank=True, db_column="isFullyWatched", null=True
            ),
        ),
    ]
