# Generated by Django 4.1.7 on 2023-03-12 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0002_alter_course_tcr_alter_lecture_crs_alter_review_crs_and_more",
        ),
        ("users", "0006_alter_videowatches_isfullywatched"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="videowatches",
            options={"managed": True, "verbose_name_plural": "Video Watches"},
        ),
        migrations.AlterField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="teachers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usercourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="userCourses",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="usercourse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="userCourses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="videowatches",
            name="lecture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="videoWatches",
                to="courses.lecture",
            ),
        ),
        migrations.AlterField(
            model_name="videowatches",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="videoWatches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
