# Generated by Django 4.1.7 on 2023-03-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="ctr_career",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user_img",
            field=models.TextField(blank=True, null=True),
        ),
    ]
