# Generated by Django 4.1.7 on 2023-03-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lctr_name", models.CharField(max_length=50)),
                ("lctr_source", models.TextField()),
                ("lctr_info", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "lecture",
                "managed": False,
            },
        ),
    ]
