# Generated by Django 4.1.7 on 2023-03-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="The date and time the object was created."
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time the objec was last updated.",
                null=True,
            ),
        ),
    ]
