# Generated by Django 4.1.7 on 2023-03-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crs_name", models.CharField(max_length=50)),
                ("crs_info", models.TextField(blank=True, null=True)),
                ("thumbnail", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "course",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lctr_name", models.CharField(max_length=50)),
                ("lctr_source", models.TextField()),
                ("lctr_info", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "lecture",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("star", models.IntegerField(blank=True, null=True)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "review",
                "managed": False,
            },
        ),
    ]
