# Generated by Django 4.1.7 on 2023-03-11 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0003_teacher"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crs_name", models.CharField(max_length=50)),
                ("crs_info", models.TextField(blank=True, null=True)),
                ("thumbnail", models.TextField(blank=True, null=True)),
                (
                    "tcr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.teacher",
                    ),
                ),
            ],
            options={
                "db_table": "course",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "star",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "★"),
                            (2, "★★"),
                            (3, "★★★"),
                            (4, "★★★★"),
                            (5, "★★★★★"),
                        ],
                        null=True,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "crs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "review",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lctr_name", models.CharField(max_length=50)),
                ("lctr_source", models.TextField()),
                ("lctr_info", models.TextField(blank=True, null=True)),
                (
                    "crs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "db_table": "lecture",
                "managed": True,
            },
        ),
    ]
