# Generated by Django 4.1.7 on 2023-03-13 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("users", "0002_videowatches_usercourse_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="tcr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="courses",
                to="users.teacher",
            ),
        ),
    ]
