# Generated by Django 4.1.7 on 2023-03-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Answer",
        ),
    ]
