# Generated by Django 4.1.7 on 2023-03-11 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lctr_name", models.CharField(max_length=50)),
                ("lctr_source", models.TextField()),
                ("lctr_info", models.TextField(blank=True, null=True)),
                (
                    "crs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "db_table": "lecture",
                "managed": True,
            },
        ),
    ]
