# Generated by Django 4.1.7 on 2023-03-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_delete_answer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"managed": True},
        ),
    ]
