# Generated by Django 4.1.7 on 2023-03-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_prcie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="prcie",
            new_name="price",
        ),
    ]
