# Generated by Django 4.1.7 on 2023-03-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_course_category_alter_course_crs_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="crs_content",
            field=models.TextField(
                blank=True,
                help_text="Content information about the course, if any.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="crs_goal",
            field=models.TextField(
                blank=True, help_text="Goal about the course, if any.", null=True
            ),
        ),
    ]
